language: r
cran: http://cran.rstudio.com
cache: packages

r_github_packages:
  - curso-r/puBuild

before_script:
  - chmod +x ./_build.sh
  - chmod +x ./_deploy.sh

script:
  - ./_build.sh
  - ./_deploy.sh