---
author: "Athos Damiani"
---

## Miscelâneas

### Vetor de letras do alfabeto

```{r}
letters
LETTERS
```

### Operadores aritméticos

```{r,  echo=FALSE, results='asis'}
op_aritmetico <- data.frame(
  "Operador" = c("x + y", "x - y", "x \\* y", 
                 "x / y", "x^y ou x\\*\\*y", 
                 "x%%y", "x%/%y"),
  "Descrição" = c("Adição de x com y", 
                  "Subtração de y em x",
                  "Multiplicaçăo de x e y", 
                  "Divisão de x por y", 
                  "x elevado a y-ésima potência",
                  "Resto da divisão de x por y (módulo)", 
                  "Parte inteira da divisão de x por y")
) 

knitr::kable(op_aritmetico)
```

### Operadores lógicos

```{r, echo=FALSE}
op_logico <- data.frame(
  "Operador" = c("x < y", "x <= y", "x > y", "x >= y", 
                 "x == y", "x != y", "!x", "x | y ", 
                 "x & y", "xor(x, y)"),
  "Descrição" = c("x menor que y?", "x menor ou igual a y?", 
                  "x maior que y?", "x maior ou igual a y?", 
                  "x igual a y?", "x diferente de y?", 
                  "Negativa de x", "x ou y são verdadeiros?", 
                  "x e y são verdadeiros?", 
                  "x ou y são verdadeiros (apenas um deles)?"))
knitr::kable(op_logico)
```

--------------------------------------------------------------------------------
